apiVersion: apps/v1
kind: Deployment
metadata:
  name: resale-content-management-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resale-content-management-app
  template:
    metadata:
      labels:
        app: resale-content-management-app
    spec:
      containers:
        - name: resale-content-management-app
          image: de.icr.io/dev-registry/loveresale-content-management-backend:latest
          args:
            - --spring.application.json=$(BINDING)
          env:
            - name: BINDING
              valueFrom:
                configMapKeyRef:
                  name: backend-properties
                  key: application-properties
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: backend-properties
                  key: DB_CONNECTION
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-properties
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-properties
                  key: DB_PASSWORD
          ports:
            - containerPort: 8025
          resources:
            requests:
              cpu: 125m
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: resale-content-management-service-cip
  labels:
    app: resale-content-management-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8025
  selector:
    app: resale-content-management-app
